apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-deployment
  labels:
    app: kuber-deployment
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
        - name: kuber-app
          image: karim58/otus-microservice-architecture:homework-1
          ports:
            - containerPort: 8000
